/** ============================================================================
 *  @dreamward/design-system — tailwind-preset.cjs
 *  Shared Tailwind preset: maps utility classes onto the --rz-* tokens.
 *  Apps consume via:  presets: [require('@dreamward/design-system/tailwind-preset')]
 *  ========================================================================= */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-mode="dark"]'],
  theme: {
    extend: {
      borderRadius: {
        xs: 'var(--rz-radius-xs)',
        sm: 'var(--rz-radius-sm)',
        md: 'var(--rz-radius-md)',
        lg: 'var(--rz-radius-lg)',
        xl: 'var(--rz-radius-xl)',
        full: 'var(--rz-radius-full)',
      },
      colors: {
        background: 'var(--rz-bg)',
        foreground: 'var(--rz-fg)',
        card: { DEFAULT: 'var(--rz-bg-raised)', foreground: 'var(--rz-fg)' },
        popover: { DEFAULT: 'var(--rz-bg-sunken)', foreground: 'var(--rz-fg)' },
        primary: { DEFAULT: 'var(--rz-accent)', foreground: 'var(--rz-accent-fg)' },
        secondary: { DEFAULT: 'var(--rz-surface)', foreground: 'var(--rz-fg)' },
        muted: { DEFAULT: 'var(--rz-bg-sunken)', foreground: 'var(--rz-fg-muted)' },
        accent: { DEFAULT: 'var(--rz-bg-sunken)', foreground: 'var(--rz-fg)' },
        destructive: { DEFAULT: 'var(--rz-danger)', foreground: '#ffffff' },
        border: 'var(--rz-border)',
        'border-strong': 'var(--rz-border-strong)',
        input: 'var(--rz-surface)',
        ring: 'var(--rz-accent)',
        'brand-yellow': 'var(--rz-accent)',
        'brand-yellow-hover': 'var(--rz-accent-strong)',
        'bg-elevated': 'var(--rz-bg-sunken)',
        'bg-sunken': 'var(--rz-bg-sunken)',
        'bg-raised': 'var(--rz-bg-raised)',
        'bg-card-hover': 'var(--rz-surface-hover)',
        surface: 'var(--rz-surface)',
        'surface-hover': 'var(--rz-surface-hover)',
        'fg-muted': 'var(--rz-fg-muted)',
        'fg-subtle': 'var(--rz-fg-subtle)',
        'fg-faint': 'var(--rz-fg-faint)',
        success: 'var(--rz-success)',
        'success-soft': 'var(--rz-success-soft)',
        warning: 'var(--rz-warning)',
        'warning-soft': 'var(--rz-warning-soft)',
        danger: 'var(--rz-danger)',
        'danger-soft': 'var(--rz-danger-soft)',
        info: 'var(--rz-info)',
        'info-soft': 'var(--rz-info-soft)',
      },
      fontFamily: {
        sans: ['Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        hebrew: ['Rubik', 'Poppins', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
        display: ['Poppins', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        '2xs': 'var(--rz-text-2xs)',
        xs: 'var(--rz-text-xs)',
        sm: 'var(--rz-text-sm)',
        base: 'var(--rz-text-base)',
        md: 'var(--rz-text-md)',
        lg: 'var(--rz-text-lg)',
        xl: 'var(--rz-text-xl)',
        '2xl': 'var(--rz-text-2xl)',
        '3xl': 'var(--rz-text-3xl)',
        '4xl': 'var(--rz-text-4xl)',
        '5xl': 'var(--rz-text-5xl)',
        '6xl': 'var(--rz-text-6xl)',
      },
      boxShadow: {
        'rz-1': 'var(--rz-shadow-1)',
        'rz-2': 'var(--rz-shadow-2)',
        'rz-3': 'var(--rz-shadow-3)',
        glow: 'var(--rz-shadow-glow)',
      },
      maxWidth: { site: '1200px' },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-up': { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'popup-in': { from: { opacity: '0', transform: 'scale(0.95) translateY(10px)' }, to: { opacity: '1', transform: 'scale(1) translateY(0)' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        'float-slow': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-up': 'fade-up 0.5s var(--rz-ease-out) forwards',
        'fade-in': 'fade-in 0.5s var(--rz-ease-out) forwards',
        'popup-in': 'popup-in 0.3s var(--rz-ease-out) forwards',
        float: 'float 4s ease-in-out infinite',
        'float-slow': 'float-slow 6s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
